api_platform:
    title: Hello API Platform Platform Mikro
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_swagger_ui: true
    enable_re_doc: false
    enable_docs: true
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Entity']
