nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['*']
    max_age: 3600
    allow_credentials: false
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      max_age: 3600
      allow_credentials: false
