security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            custom_authenticators:
                - App\Security\KeycloakAuthenticator
            stateless: true

    access_control:
        - { path: ^/api, roles: ROLE_USER }