services:
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: Europe/Warsaw
        container_name: php
        volumes:
            - ./:/app
            - './docker/php/conf.d:/usr/local/etc/php/conf.d'
            - 'php_composer_data:/root/.composer'
        networks:
            - network_main
            - network_rabbit
            - sandbox-network
    platform-www:
        build: ./docker/www
        container_name: platform-www
        ports:
            - 8084:80
        volumes:
            - ./:/app
            - ./docker/www/conf.d:/etc/nginx/conf.d
        networks:
            - network_main
            - sandbox-network

    platform-db:
        image: postgres:latest
        container_name: platform-db
        volumes:
            - platform_db_data:/var/lib/postgresql/data
        networks:
            - network_main
            - sandbox-network
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=platform
            - POSTGRES_PASSWORD=platform
            - POSTGRES_DB=platform
            - TZ=Europe/Warsaw
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U platform"]
            interval: 10s
            timeout: 5s
            retries: 5

    mercure:
        image: dunglas/mercure
        container_name: mercure
        restart: unless-stopped
        ports:
            - 3000:80
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_TRANSPORT_URL: 'bolt://mercure.db'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins *
                anonymous
        networks:
            - network_main
            - sandbox-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - mercure_data:/data
            - mercure_config:/config

volumes:
    platform_db_data:
    mercure_data:
    mercure_config:
    php_composer_data:

networks:
  network_main:
    name: network_main
    driver: bridge
  network_rabbit:
    external: true
    name: network_rabbit
  sandbox-network:
    external: true
    name: sandbox-network