#nelmio_api_doc:
#  path: /api/doc
#  controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController::index

#nelmio_api_doc_json:
#    path: /api/doc.json
#    controller: nelmio_api_doc.controller.swagger
